### ISSUE TITLE
Upload page - text edit

### ISSUE THREAD

**Issue by tahearn** [episphere/dataplatform#13]
In Journal information &  Upload data section (new text shown in BOLD):

1. please update label to read,  "**Month and** **y**ear of **m**anuscript **a**cceptance"

2. please update label to read, "Please provide the **j**ournal **n**ame and **a**cronym *.  The journal acronym can be located in using the [National Library of Medicine Catalog Database](https://www.ncbi.nlm.nih.gov/nlmcatalog/journals/).

3. lower case "m":  "Title of **m**anuscript"

4.  please update title of section to read "Upload Manuscript Data**,** Data Dictionary**, and Other Associated Metadata**"

**Comment by bkop-ds** [comment]
complete, ready for merge
