### ISSUE TITLE
Upload page - Folder and file descriptions

### ISSUE THREAD

**Issue by tahearn** [episphere/dataplatform#14]
Just a reminder, we need to add a folder description to the Box folder created for the publication. This should include the:
1. Title of the manuscript
2. The study/studies that are included in the manuscript (this information will come from the DSM plan, we just need the study name, not the CAS #)
I think it would be best if this information is can be automatically generated - don't ask the uploader to provide it.

We should make it a requirement that people need to provide a description of the files they are uploading. Don't let people upload if the description field is empty.

Please update the "+DATA" button to read, "+Data or Metadata"

**Comment by bkop-ds** [comment]
issue complete, needs merging
