### ISSUE TITLE
Public About Page  - add link to NIH data sharing policy

### ISSUE THREAD

**Issue by tahearn** [episphere/dataplatform#3]
Please add a hyperlink to the NIH Data Sharing Policy.

"DCEG is committed to sharing research data according to the [NIH Data Sharing Policy] (https://sharing.nih.gov/data-management-and-sharing-policy/about-data-management-and-sharing-policies/data-management-and-sharing-policy-overview) following FAIR principles to further advance science, improve public health, while maximizing contributions from research participants.

**Comment by Sahar-behpour** [comment]
done
