### ISSUE TITLE
About page - small edits to text

### ISSUE THREAD

**Issue by tahearn** [episphere/dataplatform#4]
Please add Bolded text

DCEG Epidemiology Data Platforms support data sharing from:

- Consortia of Studies **that are coordinated by DCEG**

- **DCEG** Research Studies

- **DCEG** Publications

**Comment by Sahar-behpour** [comment]
This has been completed in the branch "cdegedits".

**Comment by tahearn** [comment]
The new text should not be bolded. I only bolded the text just to highlight the new text. Please leave the new text, but remove the bold effect.
Thanks

**Comment by Sahar-behpour** [comment]
This has been completed in the branch "cdegedits".
