### ISSUE TITLE
Data Access Proposal Form - Add text

### ISSUE THREAD

**Issue by tahearn** [episphere/dataplatform#41]
Can you edit the text on this page to read:

"To request access to DCEG data on the Publication Data Repository, please use the following link to log-in with your eRA credentials. 

![image](https://github.com/episphere/dataplatform/assets/51208225/673d4570-bdbe-44e4-87ab-07793bef87b5)

Extramural researchers should use "Login.gov" to provide their eRA credentials, and NCI intramural researchers should use their PIV card credentials."

**Comment by bkop-ds** [comment]
Completed

**Comment by bkop-ds** [comment]
Completed
