### ISSUE TITLE
Consortia - Text edit

### ISSUE THREAD

**Issue by tahearn** [episphere/dataplatform#5]
Please remove Bolded text

The following are data platform for collaborative consortium projects that are coordinated by DCEG:

**The following data access procedures are planned:**
The Confluence Project: The Confluence Project is a large international project to study breast cancer genetic susceptibility in women and men of multiple ancestries, by integrating existing and new genome-wide genetic data, across several breast cancer consortia.

The Breast Cancer Risk Prediction Project (BCRPP):The BCRPP is a collaboration in the NCI Cohort Consortium Study that is developing risk prediction models for female breast across racial and ethnic groups.

**Comment by Sahar-behpour** [comment]
This has been completed in the branch "cdegedits".
