### ISSUE TITLE
Research Studies - Text edits

### ISSUE THREAD

**Issue by tahearn** [episphere/dataplatform#6]
Please add the following text before the list of research studies. Also please see the edits to the list of studies

The following are DCEG studies with data platform that provide information about the studies and instructions on requesting study data: 

Agricultural Health Study

Alpha-Tocopherol, Beta-Carotene Study

NIH-AARP Diet and Health Study

The Prostate, Lung, Colorectal and Ovarian **(PLCO)  !!!(DELETE "((PLCO)")!!!**

**Cancer Screening Trial Study  !!!!(PLEASE DELETE THIS STUDY)!!!** 

CRadiologic Technologists Study

**Comment by bkop-ds** [comment]
complete, ready to merge

**Comment by Sahar-behpour** [comment]
This has been completed in the branch "cdegedits".

**Comment by tahearn** [comment]
Please add the text above the list of studies, "The following are DCEG studies with data platform that provide information about the studies and instructions on requesting study data:"
