### ISSUE TITLE
Public landing page - update text on "Publications" button

### ISSUE THREAD

**Issue by tahearn** [episphere/dataplatform#7]
On the public landing page, the "Publications" button should say "Dataset from DCEG publications".

Currently it says, "My Manuscript Dataset from DCEG publications"

**Comment by Sahar-behpour** [comment]
This has been completed in the branch "cdegedits".

**Comment by tahearn** [comment]
On the public landing page, the "Publications" button should say "Dataset from DCEG publications".

**Comment by Sahar-behpour** [comment]
This has been completed in the branch "cdegedits".
